#!/bin/bash

if [ -z "$1" ]; then
    echo "Must pass a run name. Usage: ont_combine [RUN_NAME]"
    exit 1
fi

# The directory where scripts are stored
SCRIPT_DIR=$BRIDGE_SCRIPT_DIR
# The directory where sequence run subdirectories are installed
WORKING_DIR=$BRIDGE_WORKING_DIR

COMBINE_SCRIPT="$SCRIPT_DIR/ont_combine_fastq.sh"
ONT_SCRIPT="$SCRIPT_DIR/ont_genomesqc.sh"
NAME_DIR="$WORKING_DIR/share_file_templates"
RENAME_FILE="$NAME_DIR/renaming.tsv"
NAME_FILE="$NAME_DIR/names"
RUN_NAME="$1"
RUN_DIR="$WORKING_DIR/$RUN_NAME"
FASTQ_PASS_DIR="$RUN_DIR/fastq_pass"
FASTQ_PASS_MERGED_DIR="$FASTQ_PASS_DIR/fastq_pass_merged"
QC_DIR="$FASTQ_PASS_MERGED_DIR/qc"

if [ ! -d $SCRIPT_DIR ]; then
    echo "Directory $SCRIPT_DIR does not exist."
    exit 1
fi

if [ ! -d $WORKING_DIR ]; then
    echo "Directory $WORKING_DIR does not exist."
    exit 1
fi

if [ ! -d $RUN_DIR ]; then
    echo "Directory $RUN_DIR does not exist."
    exit 1
fi

echo "I'm running"

dos2unix $RENAME_FILE
bash $COMBINE_SCRIPT $FASTQ_PASS_DIR $FASTQ_PASS_MERGED_DIR $RENAME_FILE file
dos2unix $NAME_FILE
bash $ONT_SCRIPT $NAME_FILE $FASTQ_PASS_MERGED_DIR $QC_DIR

